### ISSUE TITLE
Group ID (enhancement)

### ISSUE THREAD

**Issue by aHVzY2g** [r10s/messenger-backend#11]
I recommend to add an extra ID tag, to the email header to prevent receiving emails from groups with the same name. Something like a small time hash.

**Comment by r10s** [comment]
Hi, this already happens, groups with the same name are no problem, see https://github.com/r10s/messenger-backend/blob/master/src/mrchat.c#L1223 

(the group name shown in the subject is only for the user, this is no technical need)
