### ISSUE TITLE
More AutoConfigurations

### ISSUE THREAD

**Issue by r10s** [r10s/messenger-backend#5]
More automatic configurations and initial tests. Wherever possible, E-mail-address and password should be enough.

**Comment by aHVzY2g** [comment]
Most providers work with an autodiscovery XML, probably that's a esay way to start.

```
<?xml version="1.0" encoding="UTF-8"?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
  <Response xmlns="http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a">
    <Account>
      <AccountType>email</AccountType>
      <Action>settings</Action>
      <!-- IMAP+STARTTLS on port 143 -->
      <!-- only supported in Outlook >= 2010 -->
      <!-- IMAPS on port 993 -->
      <Protocol>
        <Server>example.de</Server>
        <SPA>off</SPA>
        <Type>IMAP</Type>
        <Port>993</Port>
        <SSL>on</SSL>
      </Protocol>
      <!-- Submission+STARTTLS on port 587 -->
      <!-- only supported in Outlook >= 2010 -->
      <!-- SMTP+STARTTLS on port 25 -->
      <!-- only supported in Outlook >= 2010 -->
      <!-- SMTPS on port 465 -->
      <Protocol>
        <Server>examplede</Server>
        <SPA>off</SPA>
        <Type>SMTP</Type>
        <Port>465</Port>
        <SSL>on</SSL>
      </Protocol>
    </Account>
  </Response>
</Autodiscover>
```

**Comment by r10s** [comment]
I've just implement _Autoconfiguration_, see  https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration and I'm also willing to implement _Autodiscover_, however, I've not found a single real-life example server for testing. Can anyone point me to some existing Servers?

**Comment by aHVzY2g** [comment]
I can provide you with an account to my server using mailcow?

**Comment by r10s** [comment]
You can send the account data to r10s at b44t dot com and we will check, if things work ASAP.

**Comment by 11111000000** [comment]
android client can't autoconfigure for email.com (smtp.mail.com) now, for example
