### ISSUE TITLE
SSL connection error when sending messages via Message Submission

### ISSUE THREAD

**Issue by andresth** [r10s/messenger-backend#9]
Hi,
I wanted to try your app, but I am unable to send messages.
With logcat I found this:
```
02-03 18:19:44.492 25328 25343 I DeltaChat: T2: Executing job #10, action 800...
02-03 18:19:44.492 25328 25343 I DeltaChat: T2: Connecting to SMTP-server "dubhe.uberspace.de:587"...
02-03 18:19:44.537 25328 25343 E DeltaChat: T2: SSL-connect failed: Unknown error code
02-03 18:19:44.537 25328 25343 E DeltaChat: 
```
It seems there is a problem with the SSL connection.

My mail provider requires _Message Submission_ on port 587 with STARTTLS.

Greetings Thomas

**Comment by r10s** [comment]
Are we talking about this stuff https://tools.ietf.org/html/rfc4409 ?

**Comment by andresth** [comment]
I think so. But as far as I understand it works just like the SMTP protocol, so this don't seem to be the problem. There is also a newer version of this RFC available https://tools.ietf.org/html/rfc6409

I think there is a problem with the use of STARTTLS.
When I use my gmx.de mail account I can send messages, but they use SSL on port 465 (which used to be smtps once) and not STARTTLS.

**Comment by r10s** [comment]
Okay, thank you. We'll keep this issue open; I think someone will solve it sooner or later :-)

**Comment by r10s** [comment]
seel also https://github.com/r10s/messenger-android/issues/24

**Comment by r10s** [comment]
see also https://github.com/r10s/messenger-android/issues/46

**Comment by r10s** [comment]
STARTTLS should work with the upcoming 0.1.22
